FROM rocker/shiny-verse
RUN sudo apt update && sudo apt install -y libxt-dev
RUN sudo apt -y upgrade
RUN sudo apt install -y vim nano
RUN sudo apt install -y libxml2 libxml2-dev libudunits2-dev
RUN install2.r tidyverse httr jsonlite plotly flexdashboard DT
COPY hdbResalePrices /srv/shiny-server/hdbResalePrices